### ISSUE TITLE
Wyciąganie NSV z bety

### ISSUE THREAD

**Issue by d-sandmann** [aq33/NSV13#100]
#  naprawić mapy;
## ATLAS 
- [x] jak jest juz skonczony to @Joker66613 odhacz 
- naprawiono kilkoro niedociągnięć takie jak brak wody dla woźnego, 
- dodano bibliotekę,
- wirologie, 
- gulag, 
- shield gen
- powiększenie hangaru i dodanie dropship'u do abordaży
-  oraz wiele autorskich zmian, takie jak nowe tunele techniczne dla przykładu lub nazwa statku napisana na poszyciu
## SNEJK
- [ ]  dodanie udźwiękowiania do wszystkiego, z czym można mieć interakcję
- [ ] poprawić i dobrze zbalansować broń oraz zbroje/ubrania
- [ ]  więcej celów dla antagonistów
- [x] tłumaczenia
- [x] polskie głosy zamiast angielskiego dla komunikatów
- [ ] naprawa interakcji niektórych ubrań z NSV takie jak webbing engi lub pancerze
- [ ] zmienić ore magnet z debilnego na normalny
- [ ] udźwięczenie i dodanie nowych funkcji do hardsuitów
# co trzeba jeszcze dodać/zmienić?

**Comment by Joker66613** [comment]
Polskie głosy zrobiłem chyba dla wszystkiego. Teraz Roter dodaje efekty komputerowe i nakłada ścieżki dźwiękowe.
Snake wypada z maintainu, bo jedna osoba (Smorgli) na 4 mapy to zdecydowanie za dużo.
Cele antagów zbierałem już kiedyś z innych kodów i są tutaj https://github.com/aq33/tgstation/issues/478
Dźwięki zbiorę i dam komuś do implementacji, jak będę mieć powiedzmy pełną listę.
Broń to dalej znak zapytania

**Comment by d-sandmann** [comment]
zaktualizowano
