### ISSUE TITLE
ERT wzywane przez załogę

### ISSUE THREAD

**Issue by Joker66613** [aq33/NSV13#108]
Możliwość wezwania ERT z konsoli na w sec lub command. W tym PR była to jakaś słabsza wersja. W każdym razie potrzeba czegoś takiego na wypadek murderbone'u
https://github.com/tgstation/tgstation/pull/27342

**Comment by smorgli** [comment]
Tego nie ma juz?

**Comment by Joker66613** [comment]
Na pewno nie ma. To nigdy nie weszło. U nas jedynie można poprosić admina poprzez konsolę.
