### ISSUE TITLE
Asteroidy z modułu eksploracji Bee 

### ISSUE THREAD

**Issue by Joker66613** [aq33/NSV13#111]
Jeśli zgadza się ich rozmiar, to można je dodać jako asteroidy do zwiedzania przez górników. Jeśli są za duże, to można je pociąć.

**Comment by smorgli** [comment]
Kompletnie nie wiem o które chodzi

**Comment by Joker66613** [comment]
To teraz inaczej działa, jak tak sprawdziłem. Ruiny są generowane z modułów, czyli w praktyce tego nie wykorzystamy.
