### ISSUE TITLE
Poruszanie się postaci

### ISSUE THREAD

**Issue by Joker66613** [aq33/NSV13#113]
Sporo mobów w grze ma animacje chodzenia. Brak ich w przypadku graczy jest zauważalny. Trzeba by tu zastosować jakąś sztuczkę, by nie trzeba rysować sprite'ów. Same ruszające się buty to pójście na łatwiznę. Najlepiej zaprogramować pomniejszanie się i powiększanie nóg, by to jakoś symulować. Są tego próby na innych kodach bardziej lub mniej udane.

**Comment by UnibelUnibel** [comment]
weź lepiej to zamknij człowieku i się nie kompromituj

**Comment by Joker66613** [comment]
Zbyt niski priorytet i za dużo pracy. Może kiedyś
