### ISSUE TITLE
Sranie

### ISSUE THREAD

**Issue by Joker66613** [aq33/NSV13#115]
Coś co zawsze mnie bolało, czyli bezużyteczność toalet. Dodanie tej mechaniki w końcu sprawi, że chodzenie do ubikacji ma inny cel niż użycie uplinku traitora. Daje więcej możliwości eliminacji celu. Wyciąga ze swojego stanowiska pracy role, które nigdy go nie musiały opuszczać.
Żartuję sobie, a może jestem chory na łeb? Kto to wie.

**Comment by Szyszkrzyneczka** [comment]
Jesteś niespełna rozumu?

**Comment by joookschad** [comment]
chyba cie do reszty pojebalo od tego organizowania gier

**Comment by Joker66613** [comment]
NIkt nie zrozumie geniuszu wizjonera

**Comment by SleepyJoe2137** [comment]
joker ty jednak jesteś jebnięty

**Comment by zukonake** [comment]
![image](https://github.com/aq33/NSV13/assets/14966250/9cc6f83f-38f7-4913-8b9d-fc63d2bac5f8)

**Comment by greatwizardman** [comment]
chlopaki w zarcie chodzi o kupe! Czaicie? Zabawne bo gówno, kupsztong, kał, stolec haha :-DDD ale beka ja pierdole :-)

**Comment by SleepyJoe2137** [comment]
https://github.com/aq33/NSV13/assets/68994323/8e2f8bd7-a4fc-430d-a1eb-8b55df82f133

**Comment by greatwizardman** [comment]
![image](https://github.com/aq33/NSV13/assets/103064993/9e039dff-6dde-46e2-aeb2-646ef14e5c7d)

**Comment by d-sandmann** [comment]
o nie 😨
