### ISSUE TITLE
Otwieranie drzwi szczypcami mecha

### ISSUE THREAD

**Issue by Joker66613** [aq33/NSV13#164]
https://github.com/aq33/tgstation/pull/346

**Comment by UnibelUnibel** [comment]
Jak na mój gust złe dla balansu - ktoś z mechem (potencjalnie antag) po implementacji może bez dźwięku otworzyć każde drzwi w kilka sekund, przy czym mech bije i tak wystarczająco duże obrażenia, żeby rozwalić drzwi w parę uderzeń, a przy okazji wydaje przy tym odgłos bicia, co alarmuje załogę i daje nieco wyrównane szanse na reakcje.

**Comment by Joker66613** [comment]
Wywalone, jak komuś zależy, to sobie zakoduje
