### ISSUE TITLE
Polskie przedmioty [NAGRODA]

### ISSUE THREAD

**Issue by Joker66613** [aq33/NSV13#169]
Pokrywa się z tym https://github.com/aq33/NSV13/issues/114. Tu będę kompletować listę. Można w komentarzach dodawać kolejne

- [x] Pączki
- [x] Reklamówka biedronki jak teczka
- [x] Polak bodytype (odstający brzuchol na spricie psotaci tak jak jest *short* i *tall*)
- [x] Skarpety i sandały jako buty lub opcja customizacji postacji
- [x] Kurtka Najmana
- [x] Koszulka z OTUA
- [x] Koszula Cejrowskiego
- [x] Pozostałe znaki (PODS i DECK 1/2)
- [x] Kurwinox, blaster i strój z Kapitana Bomby
- [x] Polska flaga lub oznaczenia
- [x] Cuowiek Maupa
- [x] Krzyż i godło
- [x] Maluch jako clown car

**Comment by greatwizardman** [comment]
Pączki już istnieją w grze, wystarczy jedynie podmienić

Reklamówka biedronki i lidla (obj + inhandy):   Gotowe :-)
Skiety i sandały (obj + mob):   Gotowe :-)
Kurtka Najmana (obj + mob):   Gotowe :-)
Znaki (POKŁ [1-5] i KAPS):   Gotowe :-)
Kurwinox (Niebieski i czerwony + animacja chodzenia):   Gotowe :-)
Cuowiek Maupa:   Gotowe :-)

Polskie smaczki, czyli: Godło (brązowa i czarna ramka), Krzyż (zwykły drewniany + z złotym jezuskiem), Sztandar (wolnostojący + ikony w łapce), Flaga Dowódcy Marynarki Wojennej, Flaga Polski (64x32):   Gotowe :-)

**Comment by greatwizardman** [comment]
Maluch skończony (4 dir) :-)
Strój Kapitana Bomby (obj, mob 4 dir) oraz Blaster (obj, mob 4 dir) skończone :-)
Koszulka OTUA (biała i czarna, 4 dir) skończona :-)
Polak bodytype (gruby tors, grayscale, 4 dir) skończony :-)
Koszula cejrowskiego (4 dir) skończona :-)

+ Znak SPACE oraz 8 nowych znaków departamentów (MSTK, ZAOP, INŻY, EWAK, SZPT, NAUK, OCHR, ARTY, 4 dir) :-D

Zlecenie uważam za wykonane @Joker66613
