### ISSUE TITLE
BUG automatyka amunicyjnego departamentu nie wydaje dźwięków

### ISSUE THREAD

**Issue by d-sandmann** [aq33/NSV13#186]
Tak jak na okładce, maszynki nie wydają dźwięków pracy przy torpedach/rakietach już z jakiegoś powodu.

**Comment by greatwizardman** [comment]
Podobno w tym PRze to naprawil borowik cala fabryke, nie wiem o co kaman
https://github.com/BeeStation/NSV13/pull/2588

**Comment by d-sandmann** [comment]
W PR napisane że naprawiał ale w kodzie widać że właśnie skasował

**Comment by d-sandmann** [comment]
nie błąd a feature
